parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     itwiki
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       smtp.mydomain.com
    mailer_user:       user
    mailer_password:   password
    mailer_port:       25

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt
