fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /password

fos_login_failure:
    pattern:  /login/failure
    defaults: { _controller: FOSUserBundle:Security:login }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

wiki_index:
    resource: "@WikiIndexBundle/Resources/config/routing.yml"
    prefix:   /

wiki_user:
    resource: "@WikiUserBundle/Resources/config/routing.yml"
    prefix:   /
