jms_security_extra:
    secure_all_services: true
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Wiki\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER , ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path: /
                failure_path: fos_login_failure
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key:        %secret%


    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }