jms_security_extra:
    secure_all_services: true
    expressions: true
    # method_access_control:
        # 'IntranetAdminBundle:UsersController:.*': 'hasRole("ROLE_SUPER_ADMIN")'

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Wiki\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER , ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path: /
                failure_path: fos_login_failure
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                key:        %secret% # %secret% est un parametre de parameters.yml


    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/[a-z][a-z]/catalog, roles: ROLE_PARTNER }
        # - { path: /blog/modifier/, roles: ROLE_AUTEUR }
        # - { path: /blog, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
