<?php

namespace Wiki\IndexBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Wiki\IndexBundle\Entity\Tag;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
	public function tagsRemote($searchQuery)
	{
		return $query = $this
						->createQueryBuilder('t')
						->where('t.id LIKE :search 
								OR t.name LIKE :search 
								')
						->setParameter('search','%' . $searchQuery . '%')
						->getQuery()
						->getResult();
	}
	public function search($searchQuery)
	{
		return $query = $this
						->createQueryBuilder('e')
						->leftJoin('e.customer', 'c')
						->addSelect('c')
						->leftJoin('e.type', 't')
						->addSelect('t')
						->where('e.id LIKE :search 
								OR c.id LIKE :search 
								OR c.firstname LIKE :search 
								OR c.lastname LIKE :search
								OR c.phone1 LIKE :search 
								OR c.phone2 LIKE :search 
								OR c.phone3 LIKE :search 
								OR c.phone4 LIKE :search 
								OR c.address1 LIKE :search 
								OR c.address2 LIKE :search 
								OR c.address3 LIKE :search 
								OR c.zip LIKE :search 
								OR c.city LIKE :search 
								OR c.email LIKE :search
								OR e.title LIKE :search
								OR e.description LIKE :search
								')
						->setParameter('search','%' . $searchQuery . '%')
						->getQuery()
						->getResult();
	}
}
